### ISSUE TITLE
Need help setting up in Eclipse

### ISSUE THREAD

**Issue by rayate2410** [sarahhagstrom/vort-larb#2]
Hi Sarah,

I am completely new to Django and have basic knowledge of Python. I have to develop a simple register/login/logout functionality without any use of social plugins. I have downloaded this sample project as a zip file. And when I try to import in Eclipse using "Existing project into workspace" , it does not show the sample project in the list.

Can you please provide a detailed documentation on this.

Thanks,
Aakash

**Comment by sarahhagstrom** [comment]
This sounds like an issue with Eclipse and not an issue with this repository. I'm not an Eclipse user, so I don't know what to tell you. Writing Eclipse-based documentation is definitely out of scope for this repo. Try an Eclipse support forum or Eclipse direct support. They should be a lot more help than I can be. Sorry and good luck.

**Comment by rayate2410** [comment]
Hi, can you please help me run this sample from command line or whatever
method you use? I am completely newbie in django and i am seeing that the
project structure of this sample seems somewhat different.

Thanks in advance.

Aakash
